global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API monitoring
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # MCP Recipe Server
  - job_name: 'recipe-server'
    static_configs:
      - targets: ['recipe-server:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # MCP Knowledge Server
  - job_name: 'knowledge-server'
    static_configs:
      - targets: ['knowledge-server:8002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # MCP Tool Server
  - job_name: 'tool-server'
    static_configs:
      - targets: ['tool-server:8003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Weaviate Vector Database
  - job_name: 'weaviate'
    static_configs:
      - targets: ['weaviate:8080']
    metrics_path: '/v1/metrics'
    scrape_interval: 60s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node metrics (if node_exporter is available)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093